project/tasks/forms.py
"""Tasks blueprint forms."""

from flask_wtf import Form
from wtforms import(
    StringField,
    DateField,
    IntegerField,
    SelectField,
)
from wtforms.validators import(
    InputRequired
)


class AddTaskForm(Form):
    """Add task form."""

    task_id = IntegerField()
    name = StringField('Task Name', validators=[InputRequired()])
    due_date = DateField(
        'Date Due (mm/dd/yyy)',
        validators=[InputRequired()],
        format='%m/%d/%Y'
    )
    priority = SelectField(
        'Priority',
        validators=[InputRequired()],
        choices=[
            ('1', '1'),
            ('2', '2'),
            ('3', '3'),
            ('4', '4'),
            ('5', '5'),
            ('6', '6'),
            ('7', '7'),
            ('8', '8'),
            ('9', '9'),
            ('10', '10')
        ]
    )
    status = IntegerField('Status')

project/tasks/views.py
"""Tasks Blueprint."""

from functools import wraps
import datetime

from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    render_template,
    session,
    url_for,
)

from .forms import AddTaskForm
from project import db
from project.models import Task


# config


tasks_blueprint = Blueprint('tasks', __name__)


# helper functions


def login_required(test):
    """Wrapper to require login."""
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first')
            return redirect(url_for('users.login'))
    return wrap


def open_tasks():
    """Return open tasks."""
    return db.session.query(Task) \
        .filter_by(status='1').order_by(Task.due_date.asc())


def closed_tasks():
    """Return closed tasks."""
    return db.session.query(Task) \
        .filter_by(status='0').order_by(Task.due_date.asc())


# route handlers

@tasks_blueprint.route('/tasks/')
@login_required
def tasks():
    """Display open and closed tasks."""
    return render_template(
        'tasks.html',
        form=AddTaskForm(request.form),
        open_tasks=open_tasks(),
        closed_tasks=closed_tasks(),
    )


@tasks_blueprint.route('/add/', methods=['POST'])
@login_required
def new_task():
    """Add a new task."""
    form = AddTaskForm(request.form)
    if form.validate_on_submit():
        new_task = Task(
            form.name.data,
            form.due_date.data,
            form.priority.data,
            datetime.datetime.utcnow(),
            '1',
            session['user_id']
        )
        db.session.add(new_task)
        db.session.commit()
        flash("{0} was successfully posted. Thanks.".format(new_task.name))
    return render_template(
        'tasks.html',
        form=form,
        open_tasks=open_tasks(),
        closed_tasks=closed_tasks(),
    )


@tasks_blueprint.route('/delete/<int:task_id>/')
@login_required
def delete_task(task_id):
    """Delete a task by id."""
    task = Task.query.filter_by(task_id=task_id)

    if task.first().user_id == session['user_id'] \
            or session['role'] == 'admin':
        # have to store the task name for the flash before we delete it
        task_name = task.first().name
        task.delete()
        db.session.commit()
        flash("{0} was deleted. Nice".format(task_name))
    else:
        flash("You can only delete tasks that belong to you.")
    return redirect(url_for('tasks.tasks'))


@tasks_blueprint.route('/complete/<int:task_id>/')
@login_required
def complete_task(task_id):
    """Complete a task by id."""
    task = Task.query.filter_by(task_id=task_id)

    if task.first().user_id == session['user_id'] \
            or session['role'] == 'admin':
        task.update({"status": "0"})
        db.session.commit()
        flash("{0} was completed. Nice".format(task.first().name))
    else:
        flash("You can only update tasks that belong to you.")

    return redirect(url_for('tasks.tasks'))

project/users/views.py
"""Users Blueprint."""

from functools import wraps
from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    render_template,
    session,
    url_for,
)
from sqlalchemy.exc import IntegrityError

# What does the . in .forms do?
from .forms import RegisterForm, LoginForm
from project import db, bcrypt
from project.models import User


# config


users_blueprint = Blueprint('users', __name__)


# helper functions


def login_required(test):
    """Wrapper to require login."""
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first')
            return redirect(url_for('users.login'))
    return wrap


# route handlers


@users_blueprint.route('/logout/')
@login_required
def logout():
    """Logout."""
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('name', None)
    flash('Peace!')
    return redirect(url_for('users.login'))


@users_blueprint.route('/', methods=['GET', 'POST'])
def login():
    """Login."""
    error = None
    form = LoginForm(request.form)

    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name=form.name.data).first()

            if user is not None and bcrypt.check_password_hash(
                    user.password, form.password.data):
                session['logged_in'] = True
                session['user_id'] = user.id
                session['role'] = user.role
                session['name'] = user.name
                flash("Welcome, {0}".format(user.name))
                return redirect(url_for('tasks.tasks'))
            else:
                error = 'Invalid credentials.  Please try again.'
        else:
            error = 'Both fields are required.'

    return render_template(
        'login.html',
        form=form,
        error=error
    )


@users_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    """User registration."""
    error = None
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        new_user = User(
            form.name.data,
            form.email.data,
            bcrypt.generate_password_hash(form.password.data)
        )
        try:
            db.session.add(new_user)
            db.session.commit()
            flash("Thanks for registering, {0}".format(new_user.name))
            return redirect(url_for('users.login'))
        except IntegrityError:
            error = "That username and/or email already exists."

    return render_template(
        'register.html',
        form=form,
        error=error
    )

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>whatup</title>

    <!-- Styles -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>

    <div class="navbar" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">FlaskTaskr</a>
                Oh indeed.
            </div>
            <div class="navbar-right">
                {% if session.logged_in %}
                    You are logged in as {{ session.name }}.
                {% else %}
                    You are not logged in.
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container">
        <div class="content">
            {% for message in get_flashed_messages() %}
                <div class="flash">{{ message }}</div>
            {% endfor %}

            {% if error %}
                <div class="error">Error: {{ error }}</div>
            {% endif %}

            {% block content%}
            {% endblock %}
        </div>
        <div class="footer">
            <hr>
            <p>&copy; <a href="https://www.realpython.com">Real Python</a></p>
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{url_for('static', filename='js/jquery-2.2.4.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
</body>

</html>

project/templates/login.html
{% extends "_base.html" %}
{% block content %}

<h3>Please login</h3>

{# I've omitted adding the request.form.username to this, not sure what it does #}

<form method="post" action="/">
    {{ form.csrf_token }}
    <p>
    {{ form.name(placeholder="name") }} 
    <span class="error">
    {% if form.name.errors %}
        {% for error in form.name.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    </span>
    </p>
    <p>
    {{ form.password(placeholder="password") }} 
    <span class="error">
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
    </span>
    </p>
    <button class="btn btn-small btn-success" type="submit" value="Login">Login</button>
</form>

<p>Need an account? <a href="{{ url_for('users.register') }}">Sign Up!</a></p>

{% endblock %}

project/templates/register.html
{% extends "_base.html" %}
{% block content %}

<h1>Welcome to flask task thing</h1>

<h3>Please create an account</h3>

<form method="POST" action="">
    {{ form.csrf_token }}
    <p>
    {{ form.name(placeholder="name") }} 
    {% if form.name.errors %}
        {% for error in form.name.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    </p>
    {{ form.email(placeholder="email") }} 
    {% if form.email.errors %}
        {% for error in form.email.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    </p>
    <p>
    {{ form.password(placeholder="password") }} 
    {% if form.password.errors %}
        {% for error in form.password.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    </p>
    <p>
    {{ form.confirm(placeholder="confirm password") }} 
    {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
            {{ error }}
        {% endfor %}
    {% endif %}
    </p>
    <button class="btn btn-small btn-success" type="submit" value="Register">Register</button>
</form>

{% endblock %}

project/templates/tasks.html
{% extends "_base.html" %}

{% block content %}

<div class="add-task">
    <form action="{{ url_for('tasks.new_task') }}" method="POST">
        {{ form.csrf_token }}

        {{ form.name(placeholder="name") }} 
        {% if form.name.errors %}
            {% for error in form.name.errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
        <br>
        {{ form.due_date(placeholder="due date (mm/dd/yyyy)") }} 
        {% if form.due_date.errors %}
            {% for error in form.due_date.errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
        <br>
        {{ form.priority.label }} 
        {{ form.priority }} 
        {% if form.priority.errors %}
            {% for error in form.priority.errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
        <br>
        <input class="button" type="submit" value="Save new task">
    </form>
</div>
<div class="entries">
<h2>Open Tasks</h2>
    <div class="datagrid">
        <table>
            <thead>
                <tr>
                    <th width="75px"><strong>ID</strong></th>
                    <th width="200px"><strong>Task Name</strong></th>
                    <th width="100px"><strong>Due Date</strong></th>
                    <th width="100px"><strong>Posted Date</strong></th>
                    <th width="50px"><strong>Priority</strong></th>
                    <th width="90px"><strong>Posted By</strong></th>
                    <th><strong>Actions</strong></th>
                </tr>
            </thead>
            {% for task in open_tasks %}
                <tr>
                    <td>{{ task.task_id }}</td>
                    <td>{{ task.name }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>{{ task.posted_date }}</td>
                    <td>{{ task.priority }}</td>
                    <td>{{ task.poster.name }}</td>
                    {% if task.poster.name == session.name or session.role == 'admin' %}
                    <td>
                    <a href="{{url_for('tasks.complete_task', task_id=task.task_id)}}">Complete</a>
                     | <a href="{{url_for('tasks.delete_task', task_id=task.task_id)}}">Delete</a></td>
                     {% else %}
                        <td>N/A</td>
                     {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
<br>
<br>
<div class="entries">
<h2>Closed Tasks</h2>
    <div class="datagrid">
        <table>
            <thead>
                <tr>
                    <th width="75px"><strong>ID</strong></th>
                    <th width="200px"><strong>Task Name</strong></th>
                    <th width="100px"><strong>Due Date</strong></th>
                    <th width="100px"><strong>Posted Date</strong></th>
                    <th width="50px"><strong>Priority</strong></th>
                    <th width="90px"><strong>Posted By</strong></th>
                    <th><strong>Actions</strong></th>
                </tr>
            </thead>
            {% for task in closed_tasks %}
                <tr>
                    <td>{{ task.task_id }}</td>
                    <td>{{ task.name }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>{{ task.posted_date }}</td>
                    <td>{{ task.priority }}</td>
                    <td>{{ task.poster.name }}</td>
                    {% if task.poster.name == session.name or session.role == 'admin' %}
                    <td>
                     <a href="{{url_for('tasks.delete_task', task_id=task.task_id)}}">Delete</a></td>
                     {% else %}
                        <td>N/A</td>
                     {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}